version: '3.8'

services:
  photo-viewer:
    build: ./app
    container_name: photo_viewer
    volumes:
      - photos:/mnt/photos:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8091:8091"
    environment:
  - TZ=Europe/Rome    

volumes:
  photos:
    driver: local
    driver_opts:
      type: cifs
      o: username=raspy,password=Temp1234!,vers=3.0
      device: '//192.168.100.23/home/Photos/PhotoRequest/CAPODANNO 2025/'
