version: '3.8'
services:
  bolt-app:
    image: node:18-alpine
    container_name: bolt_app
    working_dir: /app
    
    # Monta la directory ./project in /app del container
    volumes:
      - ./project:/app

    # Installa le dipendenze e avvia il server in modalità dev
    command: sh -c "npm install && npm run dev"

    # Esempio: se l'app gira sulla porta 3000
    ports:
      - "8090:8090"
