version: '3.8'
services:
  bolt-app:
    image: node:18-alpine
    container_name: bolt_app
    working_dir: /app
    volumes:
      - ./project:/app
    # Passiamo l'argomento --host 0.0.0.0 a Vite così sia accessibile fuori dal container
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "8090:5173"  # Dal tuo host:8090 --> Container:5173
